### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by andrewshrout** [divtiply/scrapy-gzip-exporters#1]
I've attempted to install this to my conda environment and it doesn't work. Adding something to the readme would be lovely.

**Comment by divtiply** [comment]
Use pip to [install from git repo](https://pip.pypa.io/en/stable/topics/vcs-support/):
```
pip install git+https://github.com/divtiply/scrapy-gzip-exporters#egg=scrapy-gzip-exporters
```
